spring.application.name=ecommerce
server.port=8080

spring.datasource.url=jdbc:h2:mem:ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=false

jwt.secret=${JWT_SECRET:apni_bohot_hi_lambee_aur_secure_secret_key_jo_32_bytes_se_badi_ho}
jwt.expiration-ms=86400000

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
